import { Router } from 'express';
import { auth } from '../middlewares/auth';
import { metricsHandler } from '../middlewares/metrics';
import { requireRole } from '../middlewares/rbac';
import { requirePrivilegedNetworkAccess } from '../middlewares/ipAllowlist';
import adminRoutes from './admin.routes';
import agentRoutes from './agent.routes';
import authRoutes from './auth.routes';
import chatRoutes from './chat.routes';
import dashboardRoutes from './dashboard.routes';
import listingRoutes, { agentRouter as agentListingRoutes } from './listing.routes';
import marketingRoutes from './marketing.routes';
import payPortalRoutes from './pay.portal.routes';
import payRoutes from './pay.routes';
import reportRoutes from './report.routes';
import savedSearchRoutes from './saved-search.routes';
import savedListingShareRoutes from './saved-listing.routes';
import userDocRoutes from './userDoc.routes';
import reservationRoutes from './reservation.routes';
import recommendationRoutes from './recommendation.routes';
import userRoutes from './user.routes';
import viewingAgentRoutes from './viewing.agent.routes';
import viewingRoutes from './viewing.routes';
import refundRequestRoutes from './refundRequest.routes';
import uploadRoutes from './upload.routes';
import notificationRoutes from './notification.routes';
import healthRoutes from './health.routes';
import canaryRoutes from './canary.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/user', userRoutes);
router.use('/agent', agentListingRoutes);
router.use('/agent', agentRoutes);
router.use('/listings', listingRoutes);
router.use('/', recommendationRoutes);
router.use('/pay', payPortalRoutes);
router.use('/', marketingRoutes);
router.use('/', payRoutes);
router.use('/', chatRoutes);
router.use('/', reportRoutes);
router.use('/saved-searches', savedSearchRoutes);
router.use('/saved-listings', savedListingShareRoutes);
router.use('/user/documents', userDocRoutes);
router.use('/reservations', reservationRoutes);
router.use('/admin', adminRoutes);
router.use('/viewings', viewingRoutes);
router.use('/agent/viewings', viewingAgentRoutes);
router.use('/refund-requests', refundRequestRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/', uploadRoutes);
router.use('/', notificationRoutes);
router.use('/', healthRoutes);
router.use('/', canaryRoutes);
router.get('/metrics', auth, requireRole(['admin']), requirePrivilegedNetworkAccess('admin'), metricsHandler);

export default router;
